name: Workflow file for CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm & dependencies
        run: npm install

      - name: Install yarn 
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && 
             echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && 
             sudo apt update && 
             sudo apt install yarn -y

      - name: Build application
        run: npm run build