name: Workflow file for CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm & dependencies
        run: npm install

      - name: Install yarn 
        run: sudo apt update

      - name: Build application
        run: pm2 list