name: Workflow file for CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm & dependencies
        run: npm install

      - name: Install yarn 
        run: npm run build

      - name: Run tests
        run: npm run serve